### ISSUE TITLE
failed to fetch initial external labels

### ISSUE THREAD

**Issue by jackyym** [improbable-eng/thanos#422] opened 2018-07-12 09:59 UTC
**Thanos, Prometheus and Golang version used**

I get error  like this "failed to fetch initial external labels...... json: cannot unmarshal number into Go value of type struct { Data struct { YAML string \"json:\\\"yaml\\\"\" } \"json:\\\"data\\\"\" }"

and my prometheus.yml  is:

```
global:
  scrape_interval:     "15s"
  evaluation_interval: "15s"

  # Attach  these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  #external_labels:
  #    region: us-east
  #    monitor: "docker-host-alpha"
  #    replica: A

# Load and evaluate rules in this file every "evaluation_interval" seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: "nodeexporter"
    scrape_interval: "5s"
    static_configs:
      - targets: ["nodeexporter:9100","xxxx:9100"]

  - job_name: "cadvisor"
    scrape_interval: "5s"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "prometheus"
    scrape_interval: "10s"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "pushgateway"
    scrape_interval: "10s"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]

  - job_name: "airflow"
    scrape_interval: "10s"
    honor_labels: true
    static_configs:
      - targets: ["xxxxx:9112"]


alerting:
  alertmanagers:
  - scheme: "http"
    static_configs:
    - targets: 
      - "alertmanager:9093"

#  - job_name: "nginx"
#    scrape_interval: 10s
#    static_configs:
#      - targets: ["nginxexporter:9113"]

#  - job_name: "aspnetcore"
#    scrape_interval: 10s
#    static_configs:
#      - targets: ["eventlog-proxy:5000", "eventlog:5000"]
```

Anyone can help me solve this problem?

**What you expected to happen**

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by Bplotka** [comment] 2018-07-12 12:43
Hello. I need more details on it to help you!

* what are your sidecar flags?
* is the Prometheus actually running next to sidecar? Is it up? 

Most likely you are pointing to wrong address, but hard to tell.

Also the issue template is to fill all the details not to ignore those (:

**Comment by Bplotka** [comment] 2018-07-13 07:08
Nope it is not right (: I don't think you can put any auth into Prometheus v1 api `"http://localhost:9090/api/v1/status/config"`. Do you use some nginx on top of it maybe? Is it really Prometheus running on 9090? Can you share your flags?

**Comment by Bplotka** [comment] 2018-07-13 07:08
Yea it must be Prometheus, can see from scrape config, but... How you configured auth on Prometheus v1 api then? (:

**Comment by jackyym** [comment] 2018-07-13 07:56
@Bplotka ,I just debug the source code and hardcode like this:
var username string = "admin"
var passwd string = "admin" 
req.SetBasicAuth(username, passwd)

then I can startup sidecar(prometheus on the same node) by:
     /thanos sidecar --prometheus.url http://localhost:9090 --tsdb.path /prometheus_data0 --grpc-address 0.0.0.0:19091 --cluster.address 0.0.0.0:19391 --cluster.advertise-address 127.0.0.1:19391  --cluster.peers 127.0.0.1:19391 --http-address 0.0.0.0:19191 --log.level=debug

But When I start  query(another node) by:
    ./thanos query --http-address 0.0.0.0:19192 --grpc-address 0.0.0.0:19092 --cluster.address 0.0.0.0:19591 --cluster.advertise-address 127.0.0.1:19591 --cluster.peers  127.0.0.1:19391 --log.level=debug

the log like this ：
level=error ts=2018-07-13T06:37:20.381500448Z caller=cluster.go:275 component=cluster msg="refresh cluster could not join peers" peers=127.0.0.1:19391
level=error ts=2018-07-13T06:38:20.381941146Z caller=cluster.go:275 component=cluster msg="refresh cluster could not join peers" peers=127.0.0.1:19391
level=error ts=2018-07-13T06:39:20.381470855Z caller=cluster.go:275 component=cluster msg="refresh cluster could not join peers" peers=127.0.0.1:19391
level=error ts=2018-07-13T06:40:20.381483567Z caller=cluster.go:275 component=cluster msg="refresh cluster could not join peers" peers=127.0.0.1:19391
level=error ts=2018-07-13T06:41:20.381465798Z caller=cluster.go:275 component=cluster msg="refresh cluster could not join peers" peers=127.0.0.1:19391
level=error ts=2018-07-13T06:42:20.38148255Z caller=cluster.go:275 component=cluster msg="refresh cluster could not join peers" peers=127.0.0.1:19391
level=error ts=2018-07-13T06:43:20.3815213Z caller=cluster.go:275 component=cluster msg="refresh cluster could not join peers" peers=127.0.0.1:19391

pls tell me how to solve this.    

thks

**Comment by jackyym** [comment] 2018-07-13 08:30
@Bplotka thank you for your quick response, add more info here:
1. we are using prom/prometheus:v2.2.0-rc.0 docker images, so the prom version should be v2.2.0, in this version seem, prom enables api auth, below is the test result. 
$ curl -l http://localhost:9090/api/v1/status/config
401 Unauthorized
$ curl -u admin:admin http://localhost:9090/api/v1/status/config
{"status":"success","data":{"yaml":"global:\n  scrape_interval: 15s\n  scrape_timeout: 10s\n  evaluation_interval: 15s\n  external_labels:\n    monitor: docker-host-alpha\n    region: us-east\n    replica: A\nalerting:\n  alertmanagers:\n  - static_configs:\n    - targets:\n      - alertmanager:9093\n    scheme: http\n    timeout: 10s\nrule_files:\n- /etc/prometheus/alert.rules\nscrape_configs:\n- job_name: nodeexporter\n  scrape_interval: 5s\n  scrape_timeout: 5s\n  metrics_path: /metrics\n  scheme: http\n  static_configs:\n  - targets:\n    - nodeexporter:9100\n    - 172.22.11.100:9100\n- job_name: cadvisor\n  scrape_interval: 5s\n  scrape_timeout: 5s\n  metrics_path: /metrics\n  scheme: http\n  static_configs:\n  - targets:\n    - cadvisor:8080\n- job_name: prometheus\n  scrape_interval: 10s\n  scrape_timeout: 10s\n  metrics_path: /metrics\n  scheme: http\n  static_configs:\n  - targets:\n    - localhost:9090\n- job_name: pushgateway\n  honor_labels: true\n  scrape_interval: 10s\n  scrape_timeout: 10s\n  metrics_path: /metrics\n  scheme: http\n  static_configs:\n  - targets:\n    - pushgateway:9091\n- job_name: airflow\n  honor_labels: true\n  scrape_interval: 10s\n  scrape_timeout: 10s\n  metrics_path: /metrics\n  scheme: http\n  static_configs:\n  - targets:\n

2. Prometheus is running without proxy

3. seems we have no way to pass the username and password in thanos, our expectation is that thaos can support auth enabled prom api.
We tried to update sidecar.go file and fun queryExternalLabels, add username and password the sidecar can startup successfully and can polling data from our prom.
func queryExternalLabels(ctx context.Context, logger log.Logger, base *url.URL) (labels.Labels, error)

4. you can easily reproduce this issues by running prom container and start thanos sidecar on the same node.
prometheus:
    image: prom/prometheus:v2.2.0-rc.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - /prometheus_data0:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
      #- '--storage.tsdb.no-lockfile'

    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

/thanos sidecar --prometheus.url http://localhost:9090 --tsdb.path /prometheus_data0 --grpc-address 0.0.0.0:19091 --cluster.address 0.0.0.0:19391 --cluster.advertise-address 127.0.0.1:19391 --cluster.peers 127.0.0.1:19391 --http-address 0.0.0.0:19191 --log.level=debug

**Comment by Bplotka** [comment] 2018-07-13 08:58
> prom enables api auth

Can you link to some documentation to this? I am not sure about this. Also why using 2.2.0 which has lots of bugs (and rc while released v2.2.0 is there - and with some bugs as well). Please use v2.2.1 or newest 2.3.2.

**Comment by serenabi** [comment] 2018-07-13 09:36
@Bplotka I do not think Prom has good document on this, we upgrade prom to v2.3.2, and use command 
curl -l http://localhost:9090/api/v1/status/config
401 Unauthorized
then, 
$ curl -u admin:admin http://localhost:9090/api/v1/status/config 
get the config returned. 
Do you have a Prom running in your hand? could you please try curl -l http://localhost:9090/api/v1/status/config? let us know your prom version and result?

**Comment by Bplotka** [comment] 2018-07-13 10:04
I cannot do that, since I don't have curl in the docker image (: However from outside of this container (even!) I can do `http://<podIP>:9090/api/v1/status/config` just fine (e.g from browser or another container in same cluster)

Can you do that from the browser for example? This is super odd and might be related to you environment an I am pretty sure:
>  do not think Prom has good document on this,
Because this auth is not Prometheus at all (:

**Comment by serenabi** [comment] 2018-07-13 10:15
@Bplotka oh...just recalled that we have enabled stefanprodan/caddy on the same node, and it is protecting prom 9090. Sorry for the wrong message... 

But I think the issue is valid.. as if we turn off caddy, we may lost privacy features.

**Comment by Bplotka** [comment] 2018-07-13 10:36
hah, I thought so ((:  BTW sharing some caddy config that protects Prom would be nice to know!

I don't think this issue is valid. For sidecar it should be always safe to just point to the real Prometheus port and put outside traffic to 9090 port secured with Caddy and proxying to Prometheus. What do you think? 

Also if you want to secure everything you need to propagate your proxies to "clients" as well, for example now Thanos query that asks for gRPC StoreAPI on sidecar should have some front proxy that adds tokens and sidecar should have caddy as well securing sidecar gRPC service (: 

As we clearly that want to implement auth logic in Thanos (same as Prometheus) itself and you have various solution to make this intercluster traffic secure, let's close this ticket.

**Closed by Bplotka** 2018-07-13 10:36 UTC
