### ISSUE TITLE
thanos store when query is working,it will stop with invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gecailong** [improbable-eng/thanos#558] opened 2018-10-08 02:56 UTC
**Thanos, Prometheus and Golang version used**
thanos:0.1.0-rc.2
Prometheus ： 
golang:go1.10.3

**What happened**
When I started looking up historical data, he showed up：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb6c242]

**What you expected to happen**
I think he can keep running and not crash

**How to reproduce it (as minimally and precisely as possible)**:
I wonder what's going on because my memory isn't low

**Full logs to relevant components**

**Anything else we need to know**

**Comment by gecailong** [comment] 2018-10-08 02:57
Full logs：
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: level=debug ts=2018-10-08T02:29:07.169142786Z caller=bucket.go:672 msg="Blocks source resolutions" blocks=240 mint=153654624600000-1538956800000 Resolution: 0"
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb6c242]
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: goroutine 6252 [running]:
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: github.com/improbable-eng/thanos/pkg/store.(*lazyPostings).Err(0xc62e5ca000, 0x0, 0x0)
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: <autogenerated>:1 +0x32
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).Err(0xc65801a000, 0xc5dc9a3000,
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: /go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:329 +0x8c
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).Err(0xc65801a060, 0xc42040c200,
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: /go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:326 +0x37
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).Err(0xc65801a150, 0xc5dc9a3000,
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: /go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:326 +0x37
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.ExpandPostings(0xf21340, 0xc65801a150, 0x0, 0x9, 0xa
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: /go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:224 +0xfb
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: github.com/improbable-eng/thanos/pkg/store.(*BucketStore).blockSeries(0xc420282280, 0xf20880, 0xc5ddc78400, 0xd32536da7c0f660
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: /go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:489 +0x152
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: github.com/improbable-eng/thanos/pkg/store.(*BucketStore).Series.func1(0xc626c794c8, 0x0)
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: /go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:715 +0xe3
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run.func1(0xc64e0a2180, 0xc5edf90230, 0xc5d53e0270)
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: /go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:38 +0x27
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: created by github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run
Oct 08 10:29:07 bje-qtt-public-store-01 thanos[22386]: /go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:37 +0xa8
Oct 08 10:29:07 bje-qtt-public-store-01 systemd[1]: thanos-store.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 08 10:29:07 bje-qtt-public-store-01 systemd[1]: Unit thanos-store.service entered failed state.
Oct 08 10:29:07 bje-qtt-public-store-01 systemd[1]: thanos-store.service failed.

**Comment by gecailong** [comment] 2018-10-08 03:13
When I turned it on, he was normal, but when I started looking up historical data, he quit unexpectedly

**Comment by gecailong** [comment] 2018-10-11 03:50
> #335 you are probably running into this

Can you make that clear？

**Comment by bwplotka** [comment] 2018-10-11 07:17
> Can you make that clear？

This is a duplicate of https://github.com/improbable-eng/thanos/issues/335 This can mean that your store has not enough memory to respond. Please move the discussion to https://github.com/improbable-eng/thanos/issues/335

**Closed by bwplotka** 2018-10-11 07:17 UTC
