### ISSUE TITLE
[sidecar] Thanos sidecar returns empty result when querying only by external_labels

### ISSUE THREAD

**Issue by homelessnessbo** [improbable-eng/thanos#1305] opened 2019-07-04 12:01 UTC
**Thanos, Prometheus and Golang version used**

thanos, version 0.5.0 (branch: HEAD, revision: 72820b3f41794140403fd04d6da82299f2c16447)
  build user:       circleci@eeac5eb36061
  build date:       20190606-10:53:12
  go version:       go1.12.5

**What happened**

Thanos query connected to a sidecar doesn't return data if a request includes ONLY labels configured in `global.external_labels` of Prometheus server

**What you expected to happen**

The opposite

**How to reproduce it (as minimally and precisely as possible)**:

Pseudo-example:

Configuration of a server:
```global:
  external_labels:
    region: europe
```

metric example: `my_metric{app="my_app", region="europe"} 1`. (one label belongs to `external_labels`)
If I make a query `{app="my_app"}` - Returns the metric as a result without warnings
If I make a query `{region="europe"}` - Returns an empty dataset + bunch “NoStore Matched” warnings.
If I make a query `{region="europe", app="my_app"}` - Returns a result and a bunch of warnings.

The problem is happening to appear on Query => Query => Sidecar chain.

**Comment by jojohappy** [comment] 2019-07-05 03:25
@homelessnessbo  Thank you for your report!

I tried to setup two query components and one Prometheus instance with sidecar follow you said in my test environment. But I could not reproduce this case in that environment. I tried to make a query `process_max_fds{region="china"}`, `process_max_fds{instance="localhost:9090,region="china"}` and `process_max_fds{instance="localhost:9090}`, there were no errors and warnings appeared.

There is my prometheus config:
```yaml
global:
  evaluation_interval: 30s
  scrape_interval: 30s
  scrape_timeout: 10s
  external_labels:
    region: china
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
```

and the flags of query component is, there is no `query.replica-label` in flags:
```yaml
args:
- "query"
- "--log.level=debug"
- "--store.sd-files=/etc/thanos/file-sd/targets.json"
- "--store.sd-interval=30s"
```

Did I reproduce your environment correctly? If I was wrong, pls tell me soon, thank you!

**Comment by OGKevin** [comment] 2019-07-05 08:26
@jojohappy you executed the query to reproduce incorrectly.

Instead of 

```
process_max_fds{region="china"}
```

you should evaluate 

```
{region="china"}
```

**Comment by jojohappy** [comment] 2019-07-05 09:08
@OGKevin Thanks! I have tried to query just `{region="china"}`, there is actually no series returned, but no errors and warnings appeared. And I have seen the discussion in slack, I'm agree with adding some test to find the problem.

**Comment by bwplotka** [comment] 2019-07-05 15:56
BTW this has to be fixed sure, but are you sure this query even makes sense? Pull ALL the metrics you have? (:

**Comment by homelessnessbo** [comment] 2019-07-05 16:08
I'd not really put any high priority on this, because it's really corner case and we only found out because we were checking consistency of labels in different local view environments.

So yeah, for us it's not a blocker in any way.

**Comment by bwplotka** [comment] 2019-07-05 18:03
Yea, I think we should do this: https://github.com/improbable-eng/thanos/pull/1310

In the same way if you do empty as  `PromQL` you will get error.

**Comment by bwplotka** [comment] 2019-07-11 09:42
Improved error and closing as intented behaviour.

**Closed by bwplotka** 2019-07-11 09:42 UTC
Labels: component: query, component: sidecar
