### ISSUE TITLE
compact: Filter time series by regular expression

### ISSUE THREAD

**Issue by jjneely** [improbable-eng/thanos#897] opened 2019-03-06 21:05 UTC
**Thanos, Prometheus and Golang version used**

Been experimenting with Thanos 0.3.2

**What happened**

We have, for some time, federated metrics that look like recording rules to give them more durability and, at some point, long term storage beyond 30-ish days.  We've set the expectations that folks can create all the raw metrics they need or want, but that data from recording rules is "important."  Perhaps a measure of application health or latency exposed on a dashboard or some other SLO style metric.

Ideally, this allows us to keep a small fraction of our data for years, and raw data for only 30-ish days.  We collect enough metric data that we do not want to be in the situation where we keep all data forever.  (Again.)

**What you expected to happen**

The Compact module has various CLI arguments to enable pruning, retention, and down sampling.  An additional set of options for specifying "only keep matching metrics after X duration matching this regex" was my initial thought.  Clearly that needs to be thought through more.  Even simplifying this to hard coding a regex for recording rules and saying `--retention.resolution-rules=30d`.

**Comment by bwplotka** [comment] 2019-05-27 12:25
I think this is duplicate of https://github.com/improbable-eng/thanos/issues/903 and this request makes sense a lot. However it requires block rewrite. Retention only removes blocks, does not look inside. ): 

Let's follow up on discussion on https://github.com/improbable-eng/thanos/issues/903 ticket.

**Closed by bwplotka** 2019-05-27 12:25 UTC
Labels: duplicate, feature request / improvement
