### ISSUE TITLE
thanos store crash

### ISSUE THREAD

**Issue by cycker** [improbable-eng/thanos#499] opened 2018-08-31 03:35 UTC
**Thanos, Prometheus and Golang version used**
thanos, version 0.1.0-rc.2 (branch: master, revision: 53e4d69ebba12baef46543468992619fcfd524ef)
  build user:       cyckercai@5606999d6400
  build date:       20180709-13:03:10
  go version:       go1.10.3

**What happened**
thanos store crash 

**What you expected to happen**
No crash

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

level=debug ts=2018-08-31T03:21:16.049687823Z caller=bucket.go:672 msg="Blocks source resolutions" blocks=5 mint=1535080573000 maxt=1535685673000 lset="{monitorNode=\"RedisB01\"}" spans="Range: 1535079600000-1535097600000 Resolution: 0"
level=debug ts=2018-08-31T03:21:16.049767837Z caller=bucket.go:672 msg="Blocks source resolutions" blocks=163 mint=1535080573000 maxt=1535685673000 lset="{monitorNode=\"RedisA01\"}" spans="Range: 1535079600000-1535680800000 Resolution: 0"
level=debug ts=2018-08-31T03:21:17.875139382Z caller=cluster.go:269 component=cluster msg="refresh cluster done" peers=192.168.1.1:18201,192.168.1.2:18201 resolvedPeers=192.168.1.1:18201,192.168.1.2:18201
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xb6c322]

goroutine 40946 [running]:
github.com/improbable-eng/thanos/pkg/store.(*lazyPostings).Seek(0xc5c65a6a80, 0xb2f22, 0xc4b30e2c40)
	<autogenerated>:1 +0x32
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).doNext(0xc5c6570ba0, 0xb2f22, 0xc51cff7001)
	/home/cyckercai/gocode/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:294 +0x47
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).Seek(0xc5c6570ba0, 0xb2ebe, 0x8c27)
	/home/cyckercai/gocode/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:322 +0x6a
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).doNext(0xc5c6570bd0, 0xb2ebe, 0xc5c6379bf0)
	/home/cyckercai/gocode/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:294 +0x47
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).Next(0xc5c6570bd0, 0xc5c5c43cc0)
	/home/cyckercai/gocode/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:315 +0x60
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.ExpandPostings(0xf21340, 0xc5c6570bd0, 0x0, 0x4, 0x4, 0xf21340, 0xc5c6570bd0)
	/home/cyckercai/gocode/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:221 +0x57
github.com/improbable-eng/thanos/pkg/store.(*BucketStore).blockSeries(0xc4200eab80, 0xf20880, 0xc5c5fd1dc0, 0x6e0e6aef0d6b6501, 0x9be0aa3f2493251f, 0xc4a619aae0, 0xc5c6a844d0, 0xc5c6981b60, 0xc5c5e43f00, 0x4, ...)
	/home/cyckercai/gocode/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:489 +0x152
github.com/improbable-eng/thanos/pkg/store.(*BucketStore).Series.func1(0x0, 0x0)
	/home/cyckercai/gocode/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:715 +0xe3
github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run.func1(0xc5c6a55f80, 0xc5c6a84540, 0xc5418be7f0)
	/home/cyckercai/gocode/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:38 +0x27
created by github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run
	/home/cyckercai/gocode/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:37 +0xa8

**Anything else we need to know**

**Comment by cycker** [comment] 2018-08-31 08:19
After I add the following parameters, it is no longer crash.
--index-cache-size=20GB 
--chunk-pool-size=40GB

**Comment by Bplotka** [comment] 2018-08-31 13:52
Thanks! Duplicate of https://github.com/improbable-eng/thanos/issues/335

But actually your info here 
```
--index-cache-size=20GB
--chunk-pool-size=40GB
```
Is super useful - this means that our bytes.Pool is not well handled. This limits the investigation radius, thanks!

**Closed by Bplotka** 2018-08-31 13:52 UTC
Labels: bug, duplicate

**Comment by bwplotka** [comment] 2018-09-18 12:54
No, we have to prepare some guide or even calculator for some capacity planning! Let's add an issue for this.
