### ISSUE TITLE
"No store matched for this query" stores="store Addr: thanos-store-gateway.monitoring.svc:10901 Labels: [] Mint: 1556602385547 Maxt: 1556964000000 filtered out"

### ISSUE THREAD

**Issue by fyqls** [improbable-eng/thanos#1119] opened 2019-05-07 04:13 UTC
**Thanos, Prometheus and Golang version used**

**What happened**

**What you expected to happen**

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by fyqls** [comment] 2019-05-07 05:42
![Uploading Selection_093.png…]()
ee

**Comment by povilasv** [comment] 2019-05-07 06:42
I think this is a duplicate of https://github.com/improbable-eng/thanos/issues/1111

**Comment by povilasv** [comment] 2019-05-07 06:42
If not please comment and I will reopen this one.

**Closed by povilasv** 2019-05-07 06:42 UTC

**Comment by ananth07reddy** [comment] 2019-07-09 15:36
> If not please ping me and I will reopen this one.

I think this should be reopened again. I have followed the ticket #1111 but I am getting the same error with 0.5.0 Thanos version.  I have a port forward to the query service then I can see that the service is up and running as like in the screenshot. 
![screenshot-127 0 0 1-8080-2019 07 09-17-24-52](https://user-images.githubusercontent.com/22779579/60901660-9c116a00-a26e-11e9-9a8b-1de18fec2486.png)
 Query service ölogs as follows: 
level=info ts=2019-07-09T15:22:49.611207388Z caller=main.go:257 component=query msg="disabled TLS, key and cert must be set to enable"
level=info ts=2019-07-09T15:22:49.611267574Z caller=query.go:455 msg="starting query node"
level=info ts=2019-07-09T15:22:49.611541239Z caller=query.go:447 component=query msg="Listening for StoreAPI gRPC" address=0.0.0.0:10901
level=info ts=2019-07-09T15:22:49.611562322Z caller=query.go:424 msg="Listening for query and metrics" address=0.0.0.0:10902
level=info ts=2019-07-09T15:22:49.619483566Z caller=storeset.go:255 component=storeset msg="adding new store to query storeset" address=10.*.*.*:10901
level=debug ts=2019-07-09T15:24:14.270874906Z caller=proxy.go:205 msg="store Addr: 10.*.*.*:10901 Labels: [] Mint: 1562328000000 Maxt: 1562680800000 filtered out"
level=warn ts=2019-07-09T15:24:14.270921826Z caller=proxy.go:209 err="No store matched for this query" stores="store Addr: 10.*.*.*:10901  Labels: [] Mint: 1562328000000 Maxt: 1562680800000 filtered out"
     args:
          - query
          - --log.level=debug
          - --query.replica-label=replica
          - --query.auto-downsampling
          - --store=dns+servicename.namespace.svc:10901

**store.log:** 
level=info ts=2019-07-09T15:33:41.148934147Z caller=factory.go:39 msg="loading bucket configuration"
level=info ts=2019-07-09T15:33:41.190229594Z caller=cache.go:172 msg="created index cache" maxItemSizeBytes=262144000 maxSizeBytes=524288000 maxItems=math.MaxInt64
level=debug ts=2019-07-09T15:33:41.190659715Z caller=store.go:144 msg="initializing bucket store"
level=debug ts=2019-07-09T15:33:43.449870761Z caller=store.go:148 msg="bucket store ready" init_duration=2.259207576s
level=info ts=2019-07-09T15:33:43.452644434Z caller=main.go:257 msg="disabled TLS, key and cert must be set to enable"
level=info ts=2019-07-09T15:33:43.452713508Z caller=store.go:191 msg="starting store node"
level=info ts=2019-07-09T15:33:43.452841347Z caller=store.go:181 msg="Listening for StoreAPI gRPC" address=0.0.0.0:10901
level=info ts=2019-07-09T15:33:43.452855234Z caller=main.go:309 msg="Listening for metrics" address=0.0.0.0:10902

Please kindly help me out on this issue.

Best regards,
Anantha
