### ISSUE TITLE
Store: Panic in github.com/improbable-eng/thanos/pkg/store.(*lazyPostings).Next

### ISSUE THREAD

**Issue by jdfalk** [improbable-eng/thanos#462] opened 2018-08-06 14:31 UTC
**Thanos, Prometheus and Golang version used**
thanos, version 0.1.0-rc.2 (branch: HEAD, revision: ecfce893d30d87fc0505acce443ecf7350289d35)
  build user:       jenkins@build
  build date:       20180727-15:58:10
  go version:       go1.10.3

**What happened**
Thanos store crashes with `panic: runtime error: invalid memory address or nil pointer dereference`

**What you expected to happen**
Thanos store to not crash

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**
[thanos-store-panic.log](https://github.com/improbable-eng/thanos/files/2262926/thanos-store-panic.log)

**Anything else we need to know**:

**Environment**:
- OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-862.3.3.el7.x86_64
- Others:

**Comment by wleese** [comment] 2018-08-16 14:44
I was able to reproduce this only briefly. At the time I was querying 7 days of non-compacted data (that is, the compactor wasn't enabled). The crashes only seemed to happen in the early lifetime of a thanos store process - once thanos store was running and failed to crash, it'd be solid. Most times it crashed within minutes of startup+querying.
Sorry for the vague information. If there's anything I can add I will.

**Comment by Bplotka** [comment] 2018-08-16 16:18
Dup of https://github.com/improbable-eng/thanos/issues/335

**Comment by Bplotka** [comment] 2018-08-16 16:19
But still, more info = better (:

**Comment by Bplotka** [comment] 2018-08-31 13:51
(closing because of duplication)

**Closed** 2018-08-31 13:51 UTC
Labels: bug, duplicate
