### ISSUE TITLE
Panic in intersectpostings

### ISSUE THREAD

**Issue by tfheen** [improbable-eng/thanos#988] opened 2019-03-28 09:43 UTC
**Thanos, Prometheus and Golang version used**

v0.3.2 from docker image:

```
thanos, version 0.3.2 (branch: HEAD, revision: 4b7320c0e45e3f48a437bd19294f569785bafb02)
  build user:       circleci@4ea007a18ffa
  build date:       20190304-17:16:56
  go version:       go1.10.8
```

**What happened**

Some time this morning, thanos store restarted after a panic. We are seeing those on a regular basis, but I'm not sure that they're all the same errors.

**What you expected to happen**

No crash.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure.

**Full logs to relevant components**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x57fe89]

goroutine 1815 [running]:
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).Seek(0xccb9d9f3e0, 0x380944, 0xccb9d9f3e0)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:348 +0x29
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).doNext(0xccb9d9f410, 0x380944, 0x1050c60)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:323 +0x47
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).Next(0xccb9d9f410, 0x57fbac)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:344 +0x60
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.ExpandPostings(0x1205820, 0xccb9d9f410, 0x4, 0x1205820, 0xccb9d9f410, 0xc8210c58c0, 0x2)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:250 +0x57
github.com/improbable-eng/thanos/pkg/store.(*bucketIndexReader).ExpandedPostings(0xccdd7ea870, 0xcb8c88c660, 0x3, 0x3, 0xc8445cf9a0, 0xc8445cf9c8, 0xd286c9, 0x1082ec0, 0xc42036c2d0)
	/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:1202 +0x2e3
github.com/improbable-eng/thanos/pkg/store.(*BucketStore).blockSeries(0xc42036c2d0, 0x1204d60, 0xcc91c46800, 0x8e3a52919c36901, 0x9b6d61228e6a372b, 0xc777729bf0, 0xccdd7ea870, 0xccbd23b8c0, 0xcb8c88c660, 0x3, ...)
	/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:484 +0x8c
github.com/improbable-eng/thanos/pkg/store.(*BucketStore).Series.func1(0xccc1f06480, 0xcce5909fa8)
	/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:706 +0xe6
github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run.func1(0xccbd23b980, 0xccde15b500, 0xc5bebde600)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:38 +0x27
created by github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:37 +0xa8
```

**Comment by tfheen** [comment] 2019-03-28 09:45
Might maybe be the same as https://github.com/improbable-eng/thanos/issues/874

**Comment by tfheen** [comment] 2019-03-28 09:47
It's not an OOM, the pod has 

```    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 28 Mar 2019 08:14:09 +0100
      Finished:     Thu, 28 Mar 2019 08:24:28 +0100
```

which lines up well with the container restart time.

**Comment by GiedriusS** [comment] 2019-03-28 10:33
The stack trace is the same as in #874. Maybe we should close this as it's a duplicate of it?

**Comment by bwplotka** [comment] 2019-03-28 14:18
Dup of https://github.com/improbable-eng/thanos/issues/874

**Closed by bwplotka** 2019-03-28 14:18 UTC
Labels: duplicate
