### ISSUE TITLE
Thanos Store Segmentation Fault

### ISSUE THREAD

**Issue by wleese** [improbable-eng/thanos#475] opened 2018-08-13 07:54 UTC
Prometheus 2.3.2

thanos, version 0.1.0-rc.2 (branch: master, revision: 8b7169b78f5b1cf76424cabb2e7586f7219ae11b)
  build user:       wleese@wleese-HP-EliteBook-840-G1
  build date:       20180807-10:49:28
  go version:       go1.9

**What happened**
Segmentation fault in Thanos (store).

**Full logs to relevant components**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xc19d52]
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xc19d52]

goroutine 1359 [running]:
github.com/improbable-eng/thanos/pkg/store.(*lazyPostings).Next(0xc4437b7f80, 0xc42c0ffc40)
	<autogenerated>:1 +0x32
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*removedPostings).Next(0xc42dbc3bf0, 0xc42c30a2d0)
	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:444 +0x18c
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).Next(0xc42dbc3c20, 0xc42c0ffc40)
	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:312 +0x33
goroutine 2642 [running]:
github.com/improbable-eng/thanos/pkg/store.(*lazyPostings).Next(0xc4251ea840, 0xc435a0fa80)
	<autogenerated>:1 +0x32
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*removedPostings).Next(0xc4367981b0, 0xc428422a00)
	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:444 +0x18c
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).Next(0xc4367981e0, 0xc435a0fa80)
	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:312 +0x33
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.ExpandPostings(0x14e42c0, 0xc42dbc3c20, 0x0, 0x2, 0x2, 0x14e42c0, 0xc42dbc3c20)
	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:221 +0x5a
github.com/improbable-eng/thanos/pkg/store.(*BucketStore).blockSeries(0xc42019a280, 0x14e3840, 0xc43fd10f40, 0x70e06b8c142f6501, 0x79bb7ffd5d79a0f6, 0xc4204619b0, 0xc42cf5dd50, 0xc42ce2a360, 0xc42090c800, 0x2, ...)
	/home/wleese/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:489 +0x152
github.com/improbable-eng/thanos/pkg/store.(*BucketStore).Series.func1(0x0, 0x0)
	/home/wleese/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:715 +0xe3
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.ExpandPostings(0x14e42c0, 0xc4367981e0, 0x0, 0x2, 0x2, 0x14e42c0, 0xc4367981e0)
	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:221 +0x5a
github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run.func1(0xc42ce2a660, 0xc42cf5ddc0, 0xc42342dfc0)
	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:38 +0x27
created by github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run
	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:37 +0xa8
github.com/improbable-eng/thanos/pkg/store.(*BucketStore).blockSeries(0xc4202c6380, 0x14e3840, 0xc438af8cc0, 0xb69360127a176501, 0x69294c545a022d05, 0xc420264780, 0xc43d28ff10, 0xc437f1d7a0, 0xc42e0cbb80, 0x2, ...)
	/home/wleese/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:489 +0x152
github.com/improbable-eng/thanos/pkg/store.(*BucketStore).Series.func1(0x1e, 0xe11ae4)
	/home/wleese/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:715 +0xe3
github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run.func1(0xc444352f60, 0xc43d28ff80, 0xc435a0e520)
	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:38 +0x27
created by github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run
	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:37 +0xa8

```

**Comment by wleese** [comment] 2018-08-13 09:51
Captured with debug logging for context. Still trying to reproduce reliably.

```
thanos-store-platform-001-0 thanos-store level=debug ts=2018-08-13T09:49:07.193443329Z caller=bucket.go:672 msg="Blocks source resolutions" blocks=79 mint=1531554900000 maxt=1534154400000 lset="{prometheus=\"monitoring/bolcom-dev-d0t-platform\",prometheus_replica=\"prometheus-bolcom-dev-d0t-platform-0\"}" spans="Range: 1532491200000-1534147200000 Resolution: 0"
thanos-store-platform-001-0 thanos-store level=debug ts=2018-08-13T09:49:07.193908229Z caller=bucket.go:672 msg="Blocks source resolutions" blocks=79 mint=1531554900000 maxt=1534154400000 lset="{prometheus=\"monitoring/bolcom-dev-d0t-platform\",prometheus_replica=\"prometheus-bolcom-dev-d0t-platform-1\"}" spans="Range: 1532491200000-1534147200000 Resolution: 0"
thanos-store-platform-001-1 thanos-store level=debug ts=2018-08-13T09:49:07.193274382Z caller=bucket.go:672 msg="Blocks source resolutions" blocks=79 mint=1531554900000 maxt=1534154400000 lset="{prometheus=\"monitoring/bolcom-dev-d0t-platform\",prometheus_replica=\"prometheus-bolcom-dev-d0t-platform-0\"}" spans="Range: 1532491200000-1534147200000 Resolution: 0"
thanos-store-platform-001-1 thanos-store level=debug ts=2018-08-13T09:49:07.193534463Z caller=bucket.go:672 msg="Blocks source resolutions" blocks=79 mint=1531554900000 maxt=1534154400000 lset="{prometheus=\"monitoring/bolcom-dev-d0t-platform\",prometheus_replica=\"prometheus-bolcom-dev-d0t-platform-1\"}" spans="Range: 1532491200000-1534147200000 Resolution: 0"
thanos-store-platform-001-0 thanos-store level=debug ts=2018-08-13T09:49:07.555298701Z caller=bucket.go:802 msg="series query processed" stats="&{blocksQueried:158 postingsTouched:316 postingsTouchedSizeSum:132103532 postingsFetched:158 postingsFetchedSizeSum:2008 postingsFetchCount:158 postingsFetchDurationSum:12469108389 seriesTouched:344 seriesTouchedSizeSum:21625 seriesFetched:344 seriesFetchedSizeSum:10369120 seriesFetchCount:158 seriesFetchDurationSum:17821041614 chunksTouched:1063 chunksTouchedSizeSum:79022 chunksFetched:1063 chunksFetchedSizeSum:2601797 chunksFetchCount:158 chunksFetchDurationSum:16191770190 getAllDuration:358606541 mergedSeriesCount:34 mergedChunksCount:1063 mergeDuration:2365194}"
thanos-store-platform-001-1 thanos-store level=debug ts=2018-08-13T09:49:07.567309463Z caller=bucket.go:802 msg="series query processed" stats="&{blocksQueried:158 postingsTouched:316 postingsTouchedSizeSum:132103532 postingsFetched:158 postingsFetchedSizeSum:2008 postingsFetchCount:158 postingsFetchDurationSum:13352098726 seriesTouched:344 seriesTouchedSizeSum:21625 seriesFetched:344 seriesFetchedSizeSum:10369120 seriesFetchCount:158 seriesFetchDurationSum:22480927423 chunksTouched:1063 chunksTouchedSizeSum:79022 chunksFetched:1063 chunksFetchedSizeSum:2601797 chunksFetchCount:158 chunksFetchDurationSum:12774201940 getAllDuration:370150130 mergedSeriesCount:34 mergedChunksCount:1063 mergeDuration:3256604}"
thanos-store-platform-001-0 thanos-store level=debug ts=2018-08-13T09:49:07.909097287Z caller=bucket.go:672 msg="Blocks source resolutions" blocks=79 mint=1531554900000 maxt=1534154400000 lset="{prometheus=\"monitoring/bolcom-dev-d0t-platform\",prometheus_replica=\"prometheus-bolcom-dev-d0t-platform-0\"}" spans="Range: 1532491200000-1534147200000 Resolution: 0"
thanos-store-platform-001-1 thanos-store level=debug ts=2018-08-13T09:49:07.908207883Z caller=bucket.go:672 msg="Blocks source resolutions" blocks=79 mint=1531554900000 maxt=1534154400000 lset="{prometheus=\"monitoring/bolcom-dev-d0t-platform\",prometheus_replica=\"prometheus-bolcom-dev-d0t-platform-1\"}" spans="Range: 1532491200000-1534147200000 Resolution: 0"
thanos-store-platform-001-1 thanos-store level=debug ts=2018-08-13T09:49:07.908479324Z caller=bucket.go:672 msg="Blocks source resolutions" blocks=79 mint=1531554900000 maxt=1534154400000 lset="{prometheus=\"monitoring/bolcom-dev-d0t-platform\",prometheus_replica=\"prometheus-bolcom-dev-d0t-platform-0\"}" spans="Range: 1532491200000-1534147200000 Resolution: 0"
thanos-store-platform-001-0 thanos-store level=debug ts=2018-08-13T09:49:07.909496575Z caller=bucket.go:672 msg="Blocks source resolutions" blocks=79 mint=1531554900000 maxt=1534154400000 lset="{prometheus=\"monitoring/bolcom-dev-d0t-platform\",prometheus_replica=\"prometheus-bolcom-dev-d0t-platform-1\"}" spans="Range: 1532491200000-1534147200000 Resolution: 0"
thanos-store-platform-001-0 thanos-store level=debug ts=2018-08-13T09:49:08.208866681Z caller=bucket.go:802 msg="series query processed" stats="&{blocksQueried:158 postingsTouched:316 postingsTouchedSizeSum:132103532 postingsFetched:158 postingsFetchedSizeSum:2008 postingsFetchCount:158 postingsFetchDurationSum:10302919558 seriesTouched:344 seriesTouchedSizeSum:21625 seriesFetched:344 seriesFetchedSizeSum:10369120 seriesFetchCount:158 seriesFetchDurationSum:13244029701 chunksTouched:1063 chunksTouchedSizeSum:79022 chunksFetched:1063 chunksFetchedSizeSum:2601797 chunksFetchCount:158 chunksFetchDurationSum:12392363159 getAllDuration:296532872 mergedSeriesCount:34 mergedChunksCount:1063 mergeDuration:2470120}"
thanos-store-platform-001-1 thanos-store level=debug ts=2018-08-13T09:49:08.290901049Z caller=bucket.go:802 msg="series query processed" stats="&{blocksQueried:158 postingsTouched:316 postingsTouchedSizeSum:132103532 postingsFetched:158 postingsFetchedSizeSum:2008 postingsFetchCount:158 postingsFetchDurationSum:11451201929 seriesTouched:344 seriesTouchedSizeSum:21625 seriesFetched:344 seriesFetchedSizeSum:10369120 seriesFetchCount:158 seriesFetchDurationSum:23752667450 chunksTouched:1063 chunksTouchedSizeSum:79022 chunksFetched:1063 chunksFetchedSizeSum:2601797 chunksFetchCount:158 chunksFetchDurationSum:12024485454 getAllDuration:377489600 mergedSeriesCount:34 mergedChunksCount:1063 mergeDuration:4715204}"
thanos-store-platform-001-0 thanos-store level=debug ts=2018-08-13T09:49:08.542627903Z caller=bucket.go:672 msg="Blocks source resolutions" blocks=79 mint=1531554900000 maxt=1534154400000 lset="{prometheus=\"monitoring/bolcom-dev-d0t-platform\",prometheus_replica=\"prometheus-bolcom-dev-d0t-platform-0\"}" spans="Range: 1532491200000-1534147200000 Resolution: 0"
thanos-store-platform-001-0 thanos-store level=debug ts=2018-08-13T09:49:08.543081038Z caller=bucket.go:672 msg="Blocks source resolutions" blocks=79 mint=1531554900000 maxt=1534154400000 lset="{prometheus=\"monitoring/bolcom-dev-d0t-platform\",prometheus_replica=\"prometheus-bolcom-dev-d0t-platform-1\"}" spans="Range: 1532491200000-1534147200000 Resolution: 0"
thanos-store-platform-001-1 thanos-store level=debug ts=2018-08-13T09:49:08.552062806Z caller=bucket.go:672 msg="Blocks source resolutions" blocks=79 mint=1531554900000 maxt=1534154400000 lset="{prometheus=\"monitoring/bolcom-dev-d0t-platform\",prometheus_replica=\"prometheus-bolcom-dev-d0t-platform-0\"}" spans="Range: 1532491200000-1534147200000 Resolution: 0"
thanos-store-platform-001-1 thanos-store level=debug ts=2018-08-13T09:49:08.565002175Z caller=bucket.go:672 msg="Blocks source resolutions" blocks=79 mint=1531554900000 maxt=1534154400000 lset="{prometheus=\"monitoring/bolcom-dev-d0t-platform\",prometheus_replica=\"prometheus-bolcom-dev-d0t-platform-1\"}" spans="Range: 1532491200000-1534147200000 Resolution: 0"
thanos-store-platform-001-1 thanos-store level=debug ts=2018-08-13T09:49:08.677556126Z caller=bucket.go:802 msg="series query processed" stats="&{blocksQueried:158 postingsTouched:316 postingsTouchedSizeSum:132103532 postingsFetched:0 postingsFetchedSizeSum:0 postingsFetchCount:0 postingsFetchDurationSum:0 seriesTouched:344 seriesTouchedSizeSum:21625 seriesFetched:0 seriesFetchedSizeSum:0 seriesFetchCount:0 seriesFetchDurationSum:0 chunksTouched:1063 chunksTouchedSizeSum:79022 chunksFetched:1063 chunksFetchedSizeSum:2601797 chunksFetchCount:158 chunksFetchDurationSum:10327863992 getAllDuration:109988558 mergedSeriesCount:34 mergedChunksCount:1063 mergeDuration:2189045}"
thanos-store-platform-001-0 thanos-store level=debug ts=2018-08-13T09:49:08.73629416Z caller=bucket.go:802 msg="series query processed" stats="&{blocksQueried:158 postingsTouched:316 postingsTouchedSizeSum:132103532 postingsFetched:24 postingsFetchedSizeSum:304 postingsFetchCount:24 postingsFetchDurationSum:1470319812 seriesTouched:344 seriesTouchedSizeSum:21625 seriesFetched:52 seriesFetchedSizeSum:1574640 seriesFetchCount:24 seriesFetchDurationSum:1178190683 chunksTouched:1063 chunksTouchedSizeSum:79022 chunksFetched:1063 chunksFetchedSizeSum:2601797 chunksFetchCount:158 chunksFetchDurationSum:9282954601 getAllDuration:189993125 mergedSeriesCount:34 mergedChunksCount:1063 mergeDuration:2805336}"
thanos-store-platform-001-0 thanos-store panic: runtime error: invalid memory address or nil pointer dereference
thanos-store-platform-001-0 thanos-store [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xc19dc2]
thanos-store-platform-001-0 thanos-store 
thanos-store-platform-001-0 thanos-store goroutine 7396 [running]:
thanos-store-platform-001-0 thanos-store github.com/improbable-eng/thanos/pkg/store.(*lazyPostings).Seek(0xc469ebf580, 0x7619, 0xc47a2d3f60)
thanos-store-platform-001-0 thanos-store 	<autogenerated>:1 +0x32
thanos-store-platform-001-0 thanos-store github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).doNext(0xc469fab320, 0x7619, 0xc426dd08b0)
thanos-store-platform-001-0 thanos-store 	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:294 +0x47
thanos-store-platform-001-0 thanos-store github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).Next(0xc469fab320, 0xc42920d060)
thanos-store-platform-001-0 thanos-store 	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:315 +0x60
thanos-store-platform-001-0 thanos-store github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.ExpandPostings(0x14e42c0, 0xc469fab320, 0x0, 0x2, 0x2, 0x14e42c0, 0xc469fab320)
thanos-store-platform-001-0 thanos-store 	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:221 +0x5a
thanos-store-platform-001-0 thanos-store github.com/improbable-eng/thanos/pkg/store.(*BucketStore).blockSeries(0xc42022ab00, 0x14e3840, 0xc43cee0100, 0xff44b2ee58216501, 0x5bf1bedf37ebbe06, 0xc427bad5c0, 0xc446770930, 0xc444410d20, 0xc4364e0a20, 0x2, ...)
thanos-store-platform-001-0 thanos-store 	/home/wleese/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:489 +0x152
thanos-store-platform-001-0 thanos-store github.com/improbable-eng/thanos/pkg/store.(*BucketStore).Series.func1(0x411108, 0x20)
thanos-store-platform-001-0 thanos-store 	/home/wleese/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:715 +0xe3
thanos-store-platform-001-0 thanos-store github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run.func1(0xc444411c80, 0xc4467709a0, 0xc4262f54b0)
thanos-store-platform-001-0 thanos-store 	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:38 +0x27
thanos-store-platform-001-0 thanos-store created by github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run
thanos-store-platform-001-0 thanos-store 	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:37 +0xa8
thanos-store-platform-001-0 thanos-store panic: runtime error: invalid memory address or nil pointer dereference
thanos-store-platform-001-0 thanos-store [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xc19dc2]
thanos-store-platform-001-0 thanos-store 
thanos-store-platform-001-0 thanos-store goroutine 4374 [running]:
thanos-store-platform-001-0 thanos-store github.com/improbable-eng/thanos/pkg/store.(*lazyPostings).Seek(0xc44e65d840, 0x1a77e, 0xc4793681c0)
thanos-store-platform-001-0 thanos-store 	<autogenerated>:1 +0x32
thanos-store-platform-001-0 thanos-store github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).doNext(0xc426524000, 0x1a77e, 0xc4360c54b0)
thanos-store-platform-001-0 thanos-store 	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:294 +0x47
thanos-store-platform-001-0 thanos-store github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).Next(0xc426524000, 0xc422e83be0)
thanos-store-platform-001-0 thanos-store 	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:315 +0x60
thanos-store-platform-001-0 thanos-store github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.ExpandPostings(0x14e42c0, 0xc426524000, 0x0, 0x2, 0x2, 0x14e42c0, 0xc426524000)
thanos-store-platform-001-0 thanos-store 	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:221 +0x5a
thanos-store-platform-001-0 thanos-store github.com/improbable-eng/thanos/pkg/store.(*BucketStore).blockSeries(0xc42022ab00, 0x14e3840, 0xc42b511b00, 0x836efbd49e96401, 0xdf9496a600eb1b39, 0xc42061aea0, 0xc44565ca10, 0xc42e66f740, 0xc446752ce0, 0x2, ...)
thanos-store-platform-001-0 thanos-store 	/home/wleese/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:489 +0x152
thanos-store-platform-001-0 thanos-store github.com/improbable-eng/thanos/pkg/store.(*BucketStore).Series.func1(0x1, 0x0)
thanos-store-platform-001-0 thanos-store 	/home/wleese/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:715 +0xe3
thanos-store-platform-001-0 thanos-store github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run.func1(0xc43cf9c900, 0xc44565ca80, 0xc4440dac50)
thanos-store-platform-001-0 thanos-store 	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:38 +0x27
thanos-store-platform-001-0 thanos-store created by github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run
thanos-store-platform-001-0 thanos-store 	/home/wleese/go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:37 +0xa8
```

**Comment by jojohappy** [comment] 2018-08-13 09:55
duplicate #462

**Comment by wleese** [comment] 2018-08-13 09:59
@jojohappy no need to reproduce this then?

**Comment by jojohappy** [comment] 2018-08-13 10:03
No, It just duplicate with another issue, it seems to be a bug. Thanks for your report.

**Comment by Bplotka** [comment] 2018-08-16 14:34
Let's close this one, and move discussion to https://github.com/improbable-eng/thanos/issues/462 - I will spent some time today or tomorrow to investigate in details because more & more people reproduces it.

**Comment by Bplotka** [comment] 2018-08-16 14:34
Anyway thanks for reporting we need as much details as possible!

**Closed by Bplotka** 2018-08-16 14:34 UTC
Labels: bug, duplicate
