### ISSUE TITLE
Delete Certain Metrics From Longterm Storage

### ISSUE THREAD

**Issue by midnightconman** [improbable-eng/thanos#1237] opened 2019-06-08 03:16 UTC
**Thanos, Prometheus and Golang version used**
0.5.0

**What happened**

**What you expected to happen**
I would like to be able to delete certain metrics from long-term storage. 
**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by antonio** [comment] 2019-06-08 07:46
Related: https://github.com/improbable-eng/thanos/issues/415

**Comment by bradleyhession1** [comment] 2019-06-10 14:28
Bump - we had an incorrect client sending metrics, need to do this also.

**Comment by GiedriusS** [comment] 2019-06-11 05:30
Closed in favor of #415 as this is a duplicate of it.

**Closed by GiedriusS** 2019-06-11 05:30 UTC
